### ISSUE TITLE
Cannot download scraped data on OneDrive

### ISSUE THREAD

**Issue by njustesen** [TeaPearce/Counter-Strike_Behavioural_Cloning#10]
What's the best way to download the scraped dataset? I see this when following the link. 

<img width="477" alt="Screenshot 2022-10-21 at 14 41 53" src="https://user-images.githubusercontent.com/1433421/197198394-9be13dd9-43d3-42b1-ba06-3a0d6e21f3ea.png">

**Comment by njustesen** [comment]
I also tried copying it to my own OneDrive account but it stops after 1 hour of copying (just 6 GB). Even after paying for 1 TB of space. I don't think OneDrive is very suited for sharing this much data. Could you upload it somewhere else @TeaPearce ?

**Comment by TeaPearce** [comment]
Hmm, thanks for letting me know and sorry about this issue. Let me have a think about the best way forward...

**Comment by francoromaniello** [comment]
Hello

Any news on this issue ? I have the same problem.
Is it possible to make zips of 100gb ?

**Comment by L4zyy** [comment]
Hi, thank you for sharing this great dataset.
I got the same problem here. Is there any new sharing method available?

**Comment by TeaPearce** [comment]
I actually struggled to find somewhere to host datasets of this size, and resorted to using a personal OneDrive. I suppose currently they have to be downloaded by manually selecting chunks of files of small enough size. I realize this is not ideal. If anyone has ideas about another hosting platform I'd be happy to hear.

**Comment by njustesen** [comment]
Maybe [huggingface](https://huggingface.co/)?

**Comment by TeaPearce** [comment]
OK, enough people complained about this that I finally got around to reuploading the dataset in a structure that should make downloading less painful. dataset_dm_scraped_dust2_tars contains chunks of 200 files together in .tar format.

**Comment by kxhit** [comment]
Hi @TeaPearce still have troubles downloading individual chunks of dataset_dm_scraped_dust2_tars? Is there a better solution, I vote for hosting on huggingface as well. Thank you!

I can't download file beyond 20GB according to the onedrive setting below
![image](https://github.com/user-attachments/assets/1b2144b1-4d86-4865-b39b-d36520069dab)
