### ISSUE TITLE
int too long to convert

### ISSUE THREAD

**Issue by htglvl** [TeaPearce/Counter-Strike_Behavioural_Cloning#19]
ReadProcessMemory(game, address, buffer, readlength, byref(bytesRead))
it got overflow error: int too long to convert
I fix it as ctypes.c_long(address) but I don't know if it work because the memory it spit out always 0, i don't know because I got the wrong address or the code can't read because of the way I fix it

solved: just need to add ctypes.c_void_p(address) instead of address
but bear in mind that recent cs2 offset is kinda outdated and require to check and input address manually

**Comment by TeaPearce** [comment]
thanks for sharing your solution 😊
