### ISSUE TITLE
Unable to load website

### ISSUE THREAD

**Issue by liaojiaxin97** [TeaPearce/Counter-Strike_Behavioural_Cloning#21]
Unable to load website
https://1drv.ms/u/s!AjG1JlThUkPgh1JEIxETxvaphzgC?e=2AJfA3，When I click in, it always prompts me to try again or refresh the interface

**Comment by liaojiaxin97** [comment]
The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened

**Comment by PeiPeiWow** [comment]
> The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened

so how did you deal with the problem?

**Comment by liaojiaxin97** [comment]
I just downloaded train_model and ran it briefly. The dataset could not be downloaded due to the network was always interrupted. I have to solve this problem in recent days

**Comment by liaojiaxin97** [comment]
> > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> 
> so how did you deal with the problem?

I just downloaded train_model and ran it briefly. The dataset could not be downloaded due to the network was always interrupted. I have to solve this problem in recent days

**Comment by liaojiaxin97** [comment]
> > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> 
> so how did you deal with the problem?
Are you replicating this project? We can talk about the process together

**Comment by PeiPeiWow** [comment]
> > > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> > 
> > 
> > so how did you deal with the problem?
> 
> I just downloaded train_model and ran it briefly. The dataset could not be downloaded due to the network was always interrupted. I have to solve this problem in recent days

can you open the website now?

**Comment by PeiPeiWow** [comment]
> > > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> > 
> > 
> > so how did you deal with the problem?
> > Are you replicating this project? We can talk about the process together

if you can open the website and copy the download link of datasets I have a solution to get the data.

**Comment by liaojiaxin97** [comment]
> > > > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> > > 
> > > 
> > > so how did you deal with the problem?
> > 
> > 
> > I just downloaded train_model and ran it briefly. The dataset could not be downloaded due to the network was always interrupted. I have to solve this problem in recent days
> 
> can you open the website now?

I can't open it now, but I have a partial dataset download link

**Comment by PeiPeiWow** [comment]
dataset_dm_scraped_dust2/hdf5_dm_july2021_*.hdf5

total files: 5500
approx size: 700 GB
map: dust2
gamemode: deathmatch
source: scraped from online servers
UPDATE: these files have been shifted to dataset_dm_scraped_dust2_tars/ in 200 file chunks to make downloading from onedrive less painful.

**Hi do u have the link of this dataset?**

**Comment by liaojiaxin97** [comment]
> dataset_dm_scraped_dust2/hdf5_dm_july2021_*.hdf5
> 
> total files: 5500 approx size: 700 GB map: dust2 gamemode: deathmatch source: scraped from online servers UPDATE: these files have been shifted to dataset_dm_scraped_dust2_tars/ in 200 file chunks to make downloading from onedrive less painful.
> 
> **Hi do u have the link of this dataset?**

dm_expert_dust2 ; aim_expert ;train_model 
I have links to all three.How do you download, I can't download at all

**Comment by PeiPeiWow** [comment]
> > dataset_dm_scraped_dust2/hdf5_dm_july2021_*.hdf5
> > total files: 5500 approx size: 700 GB map: dust2 gamemode: deathmatch source: scraped from online servers UPDATE: these files have been shifted to dataset_dm_scraped_dust2_tars/ in 200 file chunks to make downloading from onedrive less painful.
> > **Hi do u have the link of this dataset?**
> 
> dm_expert_dust2 ; aim_expert ;train_model I have links to all three.How do you download, I can't download at all

Small size will be downloaded easier. just click it. But size like 700GB will be interupted by the unstable network, this needs other way to access it.

**Comment by PeiPeiWow** [comment]
> > > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> > 
> > 
> > so how did you deal with the problem?
> > Are you replicating this project? We can talk about the process together

I don't know what you are working on. Our team is working on real time gen video game. So maybe our goal isn't same. I just need video game datasets like this.

**Comment by liaojiaxin97** [comment]
> > > > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> > > 
> > > 
> > > so how did you deal with the problem?
> > > Are you replicating this project? We can talk about the process together
> 
> I don't know what you are working on. Our team is working on real time gen video game. So maybe our goal isn't same. I just need video game datasets like this.
Well, I only have links to my listed datasets.and I'll post them if you need me

**Comment by PeiPeiWow** [comment]
> > > > > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> > > > 
> > > > 
> > > > so how did you deal with the problem?
> > > > Are you replicating this project? We can talk about the process together
> > 
> > 
> > I don't know what you are working on. Our team is working on real time gen video game. So maybe our goal isn't same. I just need video game datasets like this.
> > Well, I only have links to my listed datasets.and I'll post them if you need me

thank  you soooo much!

**Comment by TeaPearce** [comment]
did you both manage to access some of the data? is the connection reliable enough to download a 24GB chunk from the dataset_dm_scraped_dust2_tars folder?

**Comment by PeiPeiWow** [comment]
> did you both manage to access some of the data? is the connection reliable enough to download a 24GB chunk from the dataset_dm_scraped_dust2_tars folder?

Yes. Download it chunk by chunk, but the download requests don't be processed properly. I think this is onedrive problem. Could you put the data on a reliable cloud like google or huggingface?
![Snipaste_2024-10-17_15-09-20](https://github.com/user-attachments/assets/5b0369df-dc6f-4b2c-9870-7f835c3e73e4)
![csgo](https://github.com/user-attachments/assets/fa006401-27f4-42a6-b5e4-747dade182e0)

**Comment by PeiPeiWow** [comment]
> did you both manage to access some of the data? is the connection reliable enough to download a 24GB chunk from the dataset_dm_scraped_dust2_tars folder?

I tried all day to get the datasets, but failed.

**Comment by PeiPeiWow** [comment]
> The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened

It is not the region issue. Non-related with it.

**Comment by PeiPeiWow** [comment]
> > > > > The issue has been resolved. It was caused by slow access to onedrive in China, sometimes it can be opened and sometimes it cannot be opened
> > > > 
> > > > 
> > > > so how did you deal with the problem?
> > > > Are you replicating this project? We can talk about the process together
> > 
> > 
> > I don't know what you are working on. Our team is working on real time gen video game. So maybe our goal isn't same. I just need video game datasets like this.
> > Well, I only have links to my listed datasets.and I'll post them if you need me

well, after struggling with the datasets two days. I start to bulid a AI agent to play with video game to get the video data. Hope this will help you.

**Comment by TeaPearce** [comment]
closing this -- please follow related issue https://github.com/TeaPearce/Counter-Strike_Behavioural_Cloning/issues/25
