### ISSUE TITLE
Please make the datasets can be downloaded.

### ISSUE THREAD

**Issue by PeiPeiWow** [TeaPearce/Counter-Strike_Behavioural_Cloning#24]
Please put the data on google drive or huggingface. that's will ensure the datasets are available and users can downloading it by write a simple script not hand.

**Comment by kxhit** [comment]
@PeiPeiWow Hi were you able to download the data from onedrive successfully? It seems hard to download via a ubuntu terminal..

**Comment by PeiPeiWow** [comment]
> @PeiPeiWow Hi were you able to download the data from onedrive successfully? It seems hard to download via a ubuntu terminal..

unfortunately, this datasets are not available because they can't be downloaded.

**Comment by PeiPeiWow** [comment]
> @PeiPeiWow Hi were you able to download the data from onedrive successfully? It seems hard to download via a ubuntu terminal..

Unfortunately, these datasets are not available because they cannot be downloaded.
