### ISSUE TITLE
Can anyone successfully download this dataset?

### ISSUE THREAD

**Issue by PeiPeiWow** [TeaPearce/Counter-Strike_Behavioural_Cloning#25]
I have tried many times but failed to download this dataset, especially the 700GB one. Even though it has been split into 23GB-sized chunks, it still cannot be successfully downloaded. More importantly, I have seen that many people are facing the same issue as I am, unable to download this dataset.

I would like to ask if anyone has successfully downloaded this dataset. If so, could you please upload it to Hugging Face or Google Drive? I am willing to cover the cloud storage fees.

**Comment by TeaPearce** [comment]
I had a few queries about this now. I guess the onedrive account is being throttled because there have been too many downloads recently (before the diffusion world model paper it was stable enough). I'm not sure what to do. I looked into Hugging face before and I don't think it fulfilled the criteria for that (size limit and also need more data clearance from memory). I expect google drive would lead to similar throttling issues as onedrive. 

I'm currently thinking that hosting a torrent might be the best way forward.

**Comment by TeaPearce** [comment]
Ok, I've started the dataset migration across to hugging face here: https://huggingface.co/datasets/TeaPearce/CounterStrike_Deathmatch/tree/main. for now there's just the first .tar file uploaded, but will continue transferring across...

**Comment by PeiPeiWow** [comment]
> Ok, I've started the dataset migration across to hugging face here: https://huggingface.co/datasets/TeaPearce/CounterStrike_Deathmatch/tree/main. for now there's just the first .tar file uploaded, but will continue transferring across...

Many thanks! Hugging Face might be the ideal place to store large-size data. Our team tried various platforms such as Google Drive and Blackmaze, but we found that Hugging Face performs best overall.

**Comment by PeiPeiWow** [comment]
Thank you so much! Uploading the data to Hugging Face is quite a bit of work, and I truly appreciate all your help. I would love to buy you a cup of coffee to express my gratitude, but I’m not sure how to make that happen.

**Comment by PeiPeiWow** [comment]
> Ok, I've started the dataset migration across to hugging face here: https://huggingface.co/datasets/TeaPearce/CounterStrike_Deathmatch/tree/main. for now there's just the first .tar file uploaded, but will continue transferring across...

Could you open the sponsor option on your GitHub? It would give me a chance to express my gratitude.

**Comment by TeaPearce** [comment]
best way to thank me is to do cool things with the dataset and share them widely 😋 go build!
