### ISSUE TITLE
不要公开全部源码

### ISSUE THREAD

**Issue by JACYI** [TeaPearce/Counter-Strike_Behavioural_Cloning#4]
有些人会恶意的在商业使用这些代码

**Comment by TeaPearce** [comment]
不好意思让你等一点时间，现在都开发了！

**Comment by TeaPearce** [comment]
谢谢你的提醒，可以在[这儿](https://github.com/TeaPearce/Counter-Strike_Behavioural_Cloning/issues/1)看到我的回答。
