### ISSUE TITLE
Record Crashes

### ISSUE THREAD

**Issue by DuroDaCoder** [TeaPearce/Counter-Strike_Behavioural_Cloning#7]
Hi, I have this issue: I open dm_record_data.py, and nothing happens, I press Q and nothing happens too.
I set SHOW_IMAGE to True and window opens, that says resized that is crashing.

Video of error:

https://user-images.githubusercontent.com/48152410/152793200-c9b00f2f-64c8-449a-aae4-87947a06b05f.mp4
PS: I just requested for datasets, my email is r. h. 1234 @ gmail.com

**Comment by TeaPearce** [comment]
Hi, the script 'dm_record_data.py' is used for recording new data -- is this what you were trying to do? If so, you should also already have the game running (i.e. have joined a deathmatch) before running the script. I'm not exactly sure why it's crashing, would need more info.

Have you got the dm_run_agent.py script working?

**Comment by DuroDaCoder** [comment]
Hi, yes I am trying to record new data, and dm_run_agent.py works for me. I was in game, when trying to record. I have no idea, I tried to run screen_input.py and it works, but the script dm_record_data.py and dm_record_data_me_wasd.py doesn't work for me, I have no idea why.

**Comment by TeaPearce** [comment]
Hmm, I'd suggest debugging by gradually adding in the functionality in the dm_record_data.py script. e.g. run up to line 110 first, then add in the GSI stuff (I assume you installed the game state integration on your machine?). 

Hopefully this will narrow down the problem a bit.

**Comment by DuroDaCoder** [comment]
Sorry, but I don't really know what you mean by that. I am new at python, and I have no idea how to do that.

**Comment by DuroDaCoder** [comment]
And when I have downloaded for example dataset_dm_expert_othermaps and want to use inferno 1-10, i can just jump to step 5 in the Code Overview ?

**Comment by TeaPearce** [comment]
Agreed, if you want to train on the existing datasets you can run dm_train_model.py directly (obviously still need to update paths and choose whether to fine tune an exisiting model etc).

**Comment by DuroDaCoder** [comment]
_I changed the directories in dm_train_mode.py and changed highest_num to 10, run the script and got this:_

**starting to train...**
**Epoch 1/4**
WARNING:tensorflow:From C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\data\ops\multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.

_And my Memory is struggling now, can you explain what is happening now?_
